### ISSUE TITLE
see Copernicus tool as example of data-fetching tool

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/astro-archive#2]
https://climate.usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fclimate%2Fcds_essential_variability%2Fcds_essential_variability%2F0.2.0

**Comment by volodymyrss** [comment]
There is a netcdf viewer and a bunch of netcdf tools that can operate on them
Galaxy has something that we call collections
Those collections can contain 1000 of files
However we use them normally to run one tool over the entire collection
Creating with one run 1000 of jobs

**Comment by volodymyrss** [comment]
Galaxy has an html datatype that is fully rendered. And you can get fancy add CSS and this stuff and JS.
We can try to make the tool output html and render it. This render will preview output data by it's metadata.

**Comment by francoismg** [comment]
But the .html output has to be treated like an external download and rendered by a visualization plugin right? Or is it a way to directly render some tool outputs without having to simulate a download?

**Comment by volodymyrss** [comment]
we try to go for #3 for now. It's similar to some of what we talked before.
